const menuList = [
  {
    menuId: "1",
    menuName: "首页",
    parentId: "0",
    orderNum: "1",
    path: "/index",
    component: "",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "M",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-s-home",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "2",
    menuName: "材料管理",
    parentId: "0",
    orderNum: "2",
    path: "/materials",
    component: "",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "M",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-folder-opened",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "3",
    menuName: "产品管理",
    parentId: "0",
    orderNum: "3",
    path: "/product",
    component: "",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "M",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-folder-opened",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "4",
    menuName: "系统管理",
    parentId: "0",
    orderNum: "4",
    path: "/system",
    component: "",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "M",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-folder-opened",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "200",
    menuName: "钢材",
    parentId: "2",
    orderNum: "1",
    path: "/front/materials/steel",
    component: "front/materials/steel/index",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "C",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-tickets",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "300",
    menuName: "家具",
    parentId: "3",
    orderNum: "1",
    path: "/front/product/furniture",
    component: "front/product/furniture/index",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "C",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-tickets",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "400",
    menuName: "个人中心",
    parentId: "4",
    orderNum: "1",
    path: "/system/user/personal",
    component: "system/user/personal/index",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "C",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-tickets",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
  {
    menuId: "401",
    menuName: "用户管理",
    parentId: "4",
    orderNum: "2",
    path: "/system/user/manage",
    component: "system/user/manage/index",
    query: null,
    routeName: "",
    isFrame: 0,
    isCache: 0,
    mennuType: "C",
    visible: 0,
    status: 0,
    perms: "",
    icon: "el-icon-tickets",
    createBy: "admin",
    createTime: "",
    updateBy: "",
    updateTime: "",
    remark: "",
  },
];
export default menuList;
